Ability to hide Info and Warning Messages as a User Setting
celian-rib/vscode-webvalidation-extension pull request #30
Opened 2023-02-10 22:14 UTC by tylerslemke

- currently all or nothing, you hide all info, or all warning messages, or both
- hope to expand this later to allow the user to ignore specific types of info or warning messages, or even errors

2023-02-11 18:47 UTC, celian-rib requested changes
Hi @tylerslemke, thanks for the PR, really appreciate it!

It's a very good addition to the extension and I'm sure it will be useful to many developers.

I will release a new version of the extension as soon as we merge this PR. 👍🏻

2023-02-11 18:47 UTC, celian-rib commented on src/test/suite/extension.test.ts
> +	// });
You should either uncomment or delete this test. :)

2023-02-12 23:00 UTC, celian-rib commented
Nevermind I'll handle the cleanup :) thanks again !

2023-02-12 23:00 UTC, merged

2023-02-13 06:26 UTC, tylerslemke commented
Thanks. I shouldn't have let that sneak through!